
version: 0.1
phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket test-code-deploy-mob --output-template-file NewSamTemplate.yaml
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install chai
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - mocha test.js --reporter list
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - index.js
    - NewSamTemplate.yaml
    - test.js
