AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TestFunction:
    Properties:
      CodeUri: ./
      Description: ''
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::237676459664:role/service-role/TestingCodeDeployRole
      Runtime: nodejs6.10
      Timeout: 3
    Type: AWS::Serverless::Function
